name: My first workflow

on: push

# jobs:
 # say-hello:
 #   runs-on: ubuntu-latest
  #  steps:
  #    - name: print message
  #      run: echo "Hello"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # clone repo
        uses: actions/checkout@v4

      - name: list files
        run: ls